// Generated by CoffeeScript 1.6.3
(function() {
  var CloudKeys,
    _this = this;

  CloudKeys = (function() {
    function CloudKeys() {
      var _this = this;
      this.password = 'test';
      $('#search').keyup(function() {
        var that = this;
        _this.showItems(_this.getItems($(that).val()));
      });
    }

    CloudKeys.prototype["import"] = function(xml) {
      var e, entities, entity, entry, group, parsedXML, tag, _i, _j, _len, _len1, _ref, _ref1;
      parsedXML = $.parseXML(xml);
      entities = [];
      _ref = $(parsedXML).find('group');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        group = _ref[_i];
        tag = $(group).find('>title').text();
        _ref1 = $(group).find('entry');
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          entry = _ref1[_j];
          e = $(entry);
          entity = {};
          entity[this.encrypt('title')] = this.encrypt(e.find('title').text());
          entity[this.encrypt('username')] = this.encrypt(e.find('username').text());
          entity[this.encrypt('password')] = this.encrypt(e.find('password').text());
          entity[this.encrypt('url')] = this.encrypt(e.find('url').text());
          entity[this.encrypt('comment')] = this.encrypt(e.find('comment').text());
          entity[this.encrypt('tags')] = this.encrypt(tag);
          entities.push(entity);
        }
      }
      return console.log(entities);
    };

    CloudKeys.prototype.encrypt = function(value) {
      return String(CryptoJS.AES.encrypt(value, this.password));
    };

    CloudKeys.prototype.decrypt = function(value) {
      return CryptoJS.AES.decrypt(value, this.password);
    };

    CloudKeys.prototype.showItems = function(items) {
      var item, itemContainer, _i, _len;
      $('#items li').remove();
      itemContainer = $('#items');
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        itemContainer.append("<li>" + item.title + " <span>" + item.username + "</span></li>");
      }
    };

    CloudKeys.prototype.getItems = function(search) {
      return [
        {
          'title': 'Bla bla',
          'username': 'mthie'
        }
      ];
    };

    return CloudKeys;

  })();

  window.CloudKeys = new CloudKeys();

  $('#importLink').click(function() {
    return $('#importContainer').toggle(500);
  });

  $('#importContainer button').click(function() {
    return window.CloudKeys["import"]($('#import').val());
  });

}).call(this);
